In [1]:
# check pytorch gpu is avalible

import torch

# version
print(torch.__version__)

# check cpu and gpu device
cpu_device = torch.device('cpu')
cuda_device = torch.device('cuda')

print('gpu_device:', cpu_device)
print('cuda device{0}:'.format(torch.cuda.get_device_name(0)),  cuda_device)

# transform tensor between cpu and gpu
if torch.cuda.is_available():
    # get gpu device
    cuda_device = torch.device('cuda')
    
    # default device is cpu
    # create tensor on cpu
    x_0 = torch.rand(2, 3)
    # create tensor on cuda method 1
    x_1 = torch.rand(2, 3).cuda()
    # create tensor on cuda method 2
    x_2 = torch.rand((2 ,3), device=cuda_device)
    
    y_0 = torch.ones_like(x_1, device=cuda_device)
    
    # exexute plus in gpu
    z_0 = x_1 + y_0
    # transform tensor to cpu
    z_1 = z_0.to('cpu', dtype=torch.double)
    
    print(x_0)
    print(x_1)
    print(x_2)
    print(y_0)
    print(z_0) 
    print(z_1)
    

1.3.1
gpu_device: cpu
cuda deviceGeForce RTX 2060: cuda
tensor([[0.3536, 0.7971, 0.3799],
        [0.2110, 0.3212, 0.3842]])
tensor([[0.3578, 0.0067, 0.1944],
        [0.9394, 0.2579, 0.3824]], device='cuda:0')
tensor([[0.8969, 0.7925, 0.2236],
        [0.7228, 0.7313, 0.3151]], device='cuda:0')
tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')
tensor([[1.3578, 1.0067, 1.1944],
        [1.9394, 1.2579, 1.3824]], device='cuda:0')
tensor([[1.3578, 1.0067, 1.1944],
        [1.9394, 1.2579, 1.3824]], dtype=torch.float64)


In [2]:
# create tensor
import torch

x_1 = torch.empty(5, 3)
print(x_1)

x_2 = torch.rand(5, 3)
print(x_2)

x_3 = torch.zeros(5, 3, dtype=torch.long)
print(x_3)

x_4 = torch.tensor([2.0, 3])
print(x_4)


# reuse tensor property
x_5 = x_2.new_ones(3, 5, dtype=torch.float64)
print(x_5)

# assign new type
x_6 = torch.randn_like(x_5, dtype=torch.float)
print(x_6)

# print tensor shape
print(x_6.size())
print(x_6.shape)


tensor([[-2.0393e+34,  4.5712e-41, -2.0393e+34],
        [ 4.5712e-41,  4.4842e-44,  0.0000e+00],
        [ 1.1210e-43,  0.0000e+00, -3.5687e+05],
        [ 3.0826e-41, -2.0393e+34,  4.5712e-41],
        [-3.2495e-09,  0.0000e+00,  1.8077e-43]])
tensor([[0.4588, 0.0725, 0.3630],
        [0.9648, 0.6227, 0.7576],
        [0.7334, 0.0565, 0.6274],
        [0.0550, 0.6478, 0.9163],
        [0.0010, 0.6747, 0.3833]])
tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([2., 3.])
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.3932, -1.7211, -0.3417,  0.9892,  1.0600],
        [-2.4091, -0.7594, -1.5943,  0.8354, -1.6701],
        [-1.8651,  0.3931,  1.7805,  0.7994,  0.7682]])
torch.Size([3, 5])
torch.Size([3, 5])


In [3]:
import torch

# set random seed
torch.manual_seed(0)

# add operation
x = torch.rand(3, 5)
y = torch.rand(3, 5)

print(torch.add(x, y))

# allocate output
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

# inplace
y.add_(x)
print(y)


# indice
# note 索引出来的结果和原数据共享内存，修改索引后数据，原数据也会被修改
y = x[0, :]
y += 1
print(y)
print(x[0, :])

# index_select
y = torch.index_select(x, dim=0, index=torch.tensor([1, 2]))
print(y)

# 根据维度获取聚合值
y = torch.gather(x, dim=1, index=torch.LongTensor([[0, 0, 0], [2, 2, 4], [1, 1, 3]]))
print(y)


# change shape
print(x.shape)
y = x.view(torch.mul(x.shape[0], x.shape[1]))
print(y.shape)
print(x.shape)
z = x.view(-1, 3)
print(z.shape)
print(x.shape)

# view 返回的tensor虽然可能与原tensor的shape不同， 但是仍然共享data
# view 仅仅是改变了对这个张量的观察角度，内部数据并未改变
y += 1
print(y)
print(x) # x change follwed y

# use deep copy
# clone 会被记录在计算图中， 即梯度回传到副本时也会传到源tensor
y_cp  = x.clone().view(torch.mul(x.shape[0], x.shape[1])) # 对副本做view
y_cp += 1
print(y_cp)
print(x)



tensor([[1.0148, 1.4659, 0.8885, 0.2931, 0.5897],
        [1.3157, 1.4053, 1.2935, 1.3298, 1.0517],
        [0.9018, 1.3545, 0.0585, 0.3541, 0.6673]])
tensor([[1.0148, 1.4659, 0.8885, 0.2931, 0.5897],
        [1.3157, 1.4053, 1.2935, 1.3298, 1.0517],
        [0.9018, 1.3545, 0.0585, 0.3541, 0.6673]])
tensor([[1.0148, 1.4659, 0.8885, 0.2931, 0.5897],
        [1.3157, 1.4053, 1.2935, 1.3298, 1.0517],
        [0.9018, 1.3545, 0.0585, 0.3541, 0.6673]])
tensor([1.4963, 1.7682, 1.0885, 1.1320, 1.3074])
tensor([1.4963, 1.7682, 1.0885, 1.1320, 1.3074])
tensor([[0.6341, 0.4901, 0.8964, 0.4556, 0.6323],
        [0.3489, 0.4017, 0.0223, 0.1689, 0.2939]])
tensor([[1.4963, 1.4963, 1.4963],
        [0.8964, 0.8964, 0.6323],
        [0.4017, 0.4017, 0.1689]])
torch.Size([3, 5])
torch.Size([15])
torch.Size([3, 5])
torch.Size([5, 3])
torch.Size([3, 5])
tensor([2.4963, 2.7682, 2.0885, 2.1320, 2.3074, 1.6341, 1.4901, 1.8964, 1.4556,
        1.6323, 1.3489, 1.4017, 1.0223, 1.1689, 1.2939])
tensor([[2.4963

In [4]:
import torch

# 获取标量（scalar）的元素值
x = torch.randn(1)
print(x)
print(x.item())

# tensor 转换为 numpy
# array convert to numpy
y = x.clone().numpy()
print(y)


# broadcasting
x = torch.arange(1, 3).view(1, 2)
y = torch.arange(0, 3).view(3, 1)
print(x + y)

tensor([-0.9528])
-0.9528351426124573
[-0.95283514]
tensor([[1, 2],
        [2, 3],
        [3, 4]])


In [5]:
import torch

# memery cost
# 索引不开辟内存，运算操作会开辟新的内存
# view 返回的tensor与源tensor共享data, 但是依然是一个新的tensor, 二者id(内存地地址并不一致)
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
y = x + y
print(id(y) == id_before)

# 利用索引替换操作
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
y[:] = x + y
print(id(y) == id_before)

# 利用运算符全名函数中out参数
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
torch.add(x, y, out=y)
print(id(y) == id_before)

# 利用自加运算符
x = torch.tensor([1, 2])
y = torch.tensor([3, 4])
id_before = id(y)
y += x
print(id(y) == id_before)

False
True
True
True


In [6]:
# numpy 与 tensor 的相互转换
import torch
import numpy as np
# tensor => numpy
a = torch.ones(5)
b = a.numpy()
print(a, b)

# numpy() 所产生的数组和tensor共享相同和内存
a += 1
print(a, b)
b += 1
print(a, b)

# numpy => tensor
a = np.ones(5)
b = torch.from_numpy(a)
print(a, b)

# from_numpy() 所产生的tensor和数组共享相同和内存
a += 1
print(a, b)
b += 1
print(a, b)

# torch.tensor 会对数据进行拷贝(copy), 返回的tensor 与原来的数据不再共享内存
c = torch.tensor(a)
a +=1
print(a, c)
c += 1
print(a, c)






tensor([1., 1., 1., 1., 1.]) [1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.]) [2. 2. 2. 2. 2.]
tensor([3., 3., 3., 3., 3.]) [3. 3. 3. 3. 3.]
[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
[3. 3. 3. 3. 3.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)
[4. 4. 4. 4. 4.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)
[4. 4. 4. 4. 4.] tensor([4., 4., 4., 4., 4.], dtype=torch.float64)
